version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - appnet

  frontend:
    build:
      context: ../../../ParkEASE_FE/parcheggio-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: webappuser
      MYSQL_PASSWORD: webapppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db-data:

networks:
  appnet:
